import { PrismaClient, ProviderType } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Starting seed...');

  const categories = [
    { name: 'Entertainment', slug: 'entertainment', description: 'Streaming, TV, Movies, and Music' },
    { name: 'Software', slug: 'software', description: 'Software subscriptions and services' },
    { name: 'Gaming', slug: 'gaming', description: 'Video games and gaming subscriptions' },
    { name: 'Productivity', slug: 'productivity', description: 'Tools for work and productivity' },
    { name: 'Cloud Storage', slug: 'cloud-storage', description: 'Online file storage and backup' },
    { name: 'AI', slug: 'ai', description: 'Artificial Intelligence tools' },
    { name: 'Developer Tools', slug: 'developer-tools', description: 'Tools for software development' },
    { name: 'Music', slug: 'music', description: 'Music streaming and production' },
    { name: 'Education', slug: 'education', description: 'Learning platforms and courses' },
    { name: 'Finance', slug: 'finance', description: 'Financial tools and services' },
    { name: 'Security', slug: 'security', description: 'Security and VPN services' },
  ];

  const categoryMap = new Map();
  for (const cat of categories) {
    const createdCat = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: {},
      create: cat,
    });
    categoryMap.set(cat.slug, createdCat.id);
  }

  const providersData = [
    { name: 'Netflix', slug: 'netflix', type: ProviderType.ENTERTAINMENT, categoryId: categoryMap.get('entertainment'), logoUrl: 'https://placeholder.com/icons/netflix', websiteUrl: 'https://netflix.com', billingUrl: 'https://netflix.com/YourAccount', description: 'Watch TV shows and movies', color: '#E50914', tags: ['streaming', 'movies', 'tv'], popularity: 100, verified: true, active: true },
    { name: 'Prime Video', slug: 'prime-video', type: ProviderType.ENTERTAINMENT, categoryId: categoryMap.get('entertainment'), logoUrl: 'https://placeholder.com/icons/prime-video', websiteUrl: 'https://primevideo.com', billingUrl: 'https://amazon.com/your-account', description: 'Amazon Prime streaming', color: '#00A8E1', tags: ['streaming', 'amazon'], popularity: 95, verified: true, active: true },
    { name: 'Disney+', slug: 'disney-plus', type: ProviderType.ENTERTAINMENT, categoryId: categoryMap.get('entertainment'), logoUrl: 'https://placeholder.com/icons/disney-plus', websiteUrl: 'https://disneyplus.com', billingUrl: 'https://disneyplus.com/account', description: 'Disney streaming', color: '#113CCF', tags: ['streaming', 'disney', 'marvel'], popularity: 90, verified: true, active: true },
    { name: 'Spotify', slug: 'spotify', type: ProviderType.ENTERTAINMENT, categoryId: categoryMap.get('entertainment'), logoUrl: 'https://placeholder.com/icons/spotify', websiteUrl: 'https://spotify.com', billingUrl: 'https://spotify.com/account', description: 'Music streaming', color: '#1DB954', tags: ['music', 'audio'], popularity: 98, verified: true, active: true },
    { name: 'Apple Music', slug: 'apple-music', type: ProviderType.ENTERTAINMENT, categoryId: categoryMap.get('entertainment'), logoUrl: 'https://placeholder.com/icons/apple-music', websiteUrl: 'https://music.apple.com', billingUrl: 'https://apple.com/account', description: 'Apple music streaming', color: '#FA243C', tags: ['music', 'apple'], popularity: 85, verified: true, active: true },
    { name: 'YouTube Premium', slug: 'youtube-premium', type: ProviderType.ENTERTAINMENT, categoryId: categoryMap.get('entertainment'), logoUrl: 'https://placeholder.com/icons/youtube', websiteUrl: 'https://youtube.com', billingUrl: 'https://youtube.com/paid_memberships', description: 'Ad-free video and music', color: '#FF0000', tags: ['video', 'music', 'google'], popularity: 88, verified: true, active: true },
    { name: 'ChatGPT', slug: 'chatgpt', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('ai'), logoUrl: 'https://placeholder.com/icons/chatgpt', websiteUrl: 'https://chat.openai.com', billingUrl: 'https://platform.openai.com/account/billing', description: 'AI conversational model', color: '#10A37F', tags: ['ai', 'chat', 'openai'], popularity: 99, verified: true, active: true },
    { name: 'GitHub', slug: 'github', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('developer-tools'), logoUrl: 'https://placeholder.com/icons/github', websiteUrl: 'https://github.com', billingUrl: 'https://github.com/settings/billing', description: 'Code hosting and collaboration', color: '#181717', tags: ['dev', 'git'], popularity: 95, verified: true, active: true },
    { name: 'Microsoft 365', slug: 'microsoft-365', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('productivity'), logoUrl: 'https://placeholder.com/icons/microsoft-365', websiteUrl: 'https://microsoft365.com', billingUrl: 'https://account.microsoft.com', description: 'Office apps and cloud services', color: '#D83B01', tags: ['office', 'productivity', 'microsoft'], popularity: 92, verified: true, active: true },
    { name: 'Adobe Creative Cloud', slug: 'adobe-cc', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('productivity'), logoUrl: 'https://placeholder.com/icons/adobe-cc', websiteUrl: 'https://adobe.com', billingUrl: 'https://account.adobe.com', description: 'Creative apps', color: '#FF0000', tags: ['design', 'video'], popularity: 90, verified: true, active: true },
    { name: 'Steam', slug: 'steam', type: ProviderType.GAMING, categoryId: categoryMap.get('gaming'), logoUrl: 'https://placeholder.com/icons/steam', websiteUrl: 'https://store.steampowered.com', billingUrl: 'https://store.steampowered.com/account/', description: 'PC Gaming platform', color: '#000000', tags: ['gaming', 'pc'], popularity: 96, verified: true, active: true },
    { name: 'Epic Games', slug: 'epic-games', type: ProviderType.GAMING, categoryId: categoryMap.get('gaming'), logoUrl: 'https://placeholder.com/icons/epic-games', websiteUrl: 'https://store.epicgames.com', billingUrl: 'https://store.epicgames.com/account', description: 'Games and unreal engine', color: '#313131', tags: ['gaming', 'pc'], popularity: 85, verified: true, active: true },
    { name: 'EA App', slug: 'ea-app', type: ProviderType.GAMING, categoryId: categoryMap.get('gaming'), logoUrl: 'https://placeholder.com/icons/ea', websiteUrl: 'https://ea.com', billingUrl: 'https://myaccount.ea.com', description: 'EA games platform', color: '#FF4747', tags: ['gaming', 'ea'], popularity: 75, verified: true, active: true },
    { name: 'Ubisoft Connect', slug: 'ubisoft-connect', type: ProviderType.GAMING, categoryId: categoryMap.get('gaming'), logoUrl: 'https://placeholder.com/icons/ubisoft', websiteUrl: 'https://ubisoftconnect.com', billingUrl: 'https://account.ubisoft.com', description: 'Ubisoft games', color: '#0070FF', tags: ['gaming', 'ubisoft'], popularity: 70, verified: true, active: true },
    { name: 'Battle.net', slug: 'battlenet', type: ProviderType.GAMING, categoryId: categoryMap.get('gaming'), logoUrl: 'https://placeholder.com/icons/battlenet', websiteUrl: 'https://battle.net', billingUrl: 'https://account.battle.net', description: 'Blizzard games', color: '#00AEFF', tags: ['gaming', 'blizzard'], popularity: 80, verified: true, active: true },
    { name: 'PlayStation', slug: 'playstation', type: ProviderType.GAMING, categoryId: categoryMap.get('gaming'), logoUrl: 'https://placeholder.com/icons/playstation', websiteUrl: 'https://playstation.com', billingUrl: 'https://playstation.com/acct', description: 'Console gaming', color: '#003791', tags: ['gaming', 'console'], popularity: 90, verified: true, active: true },
    { name: 'Xbox', slug: 'xbox', type: ProviderType.GAMING, categoryId: categoryMap.get('gaming'), logoUrl: 'https://placeholder.com/icons/xbox', websiteUrl: 'https://xbox.com', billingUrl: 'https://account.microsoft.com', description: 'Console and PC gaming', color: '#107C10', tags: ['gaming', 'console'], popularity: 90, verified: true, active: true },
    { name: 'Nintendo', slug: 'nintendo', type: ProviderType.GAMING, categoryId: categoryMap.get('gaming'), logoUrl: 'https://placeholder.com/icons/nintendo', websiteUrl: 'https://nintendo.com', billingUrl: 'https://accounts.nintendo.com', description: 'Nintendo games', color: '#E60012', tags: ['gaming', 'console'], popularity: 88, verified: true, active: true },
    { name: 'Google One', slug: 'google-one', type: ProviderType.UTILITY, categoryId: categoryMap.get('cloud-storage'), logoUrl: 'https://placeholder.com/icons/google-one', websiteUrl: 'https://one.google.com', billingUrl: 'https://one.google.com/storage', description: 'Cloud storage and backup', color: '#4285F4', tags: ['storage', 'google'], popularity: 92, verified: true, active: true },
    { name: 'Dropbox', slug: 'dropbox', type: ProviderType.UTILITY, categoryId: categoryMap.get('cloud-storage'), logoUrl: 'https://placeholder.com/icons/dropbox', websiteUrl: 'https://dropbox.com', billingUrl: 'https://dropbox.com/account/plan', description: 'File hosting service', color: '#0061FF', tags: ['storage', 'file-sharing'], popularity: 85, verified: true, active: true },
    { name: 'Notion', slug: 'notion', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('productivity'), logoUrl: 'https://placeholder.com/icons/notion', websiteUrl: 'https://notion.so', billingUrl: 'https://notion.so/settings', description: 'Workspace for notes and docs', color: '#000000', tags: ['notes', 'productivity'], popularity: 88, verified: true, active: true },
    { name: 'Figma', slug: 'figma', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('productivity'), logoUrl: 'https://placeholder.com/icons/figma', websiteUrl: 'https://figma.com', billingUrl: 'https://figma.com/settings/billing', description: 'Collaborative interface design', color: '#F24E1E', tags: ['design', 'ui'], popularity: 90, verified: true, active: true },
    { name: 'Canva', slug: 'canva', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('productivity'), logoUrl: 'https://placeholder.com/icons/canva', websiteUrl: 'https://canva.com', billingUrl: 'https://canva.com/settings/billing', description: 'Graphic design platform', color: '#00C4CC', tags: ['design', 'graphics'], popularity: 89, verified: true, active: true },
    { name: 'Slack', slug: 'slack', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('productivity'), logoUrl: 'https://placeholder.com/icons/slack', websiteUrl: 'https://slack.com', billingUrl: 'https://slack.com/account/billing', description: 'Business communication', color: '#4A154B', tags: ['chat', 'work'], popularity: 91, verified: true, active: true },
    { name: 'Zoom', slug: 'zoom', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('productivity'), logoUrl: 'https://placeholder.com/icons/zoom', websiteUrl: 'https://zoom.us', billingUrl: 'https://zoom.us/billing', description: 'Video conferencing', color: '#2D8CFF', tags: ['video', 'meetings'], popularity: 90, verified: true, active: true },
    { name: 'Discord', slug: 'discord', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('productivity'), logoUrl: 'https://placeholder.com/icons/discord', websiteUrl: 'https://discord.com', billingUrl: 'https://discord.com/settings/billing', description: 'Voice and text chat', color: '#5865F2', tags: ['chat', 'gaming'], popularity: 93, verified: true, active: true },
    { name: 'Hulu', slug: 'hulu', type: ProviderType.ENTERTAINMENT, categoryId: categoryMap.get('entertainment'), logoUrl: 'https://placeholder.com/icons/hulu', websiteUrl: 'https://hulu.com', billingUrl: 'https://hulu.com/account', description: 'Streaming TV and movies', color: '#1CE783', tags: ['streaming', 'tv'], popularity: 82, verified: true, active: true },
    { name: 'Max', slug: 'max', type: ProviderType.ENTERTAINMENT, categoryId: categoryMap.get('entertainment'), logoUrl: 'https://placeholder.com/icons/max', websiteUrl: 'https://max.com', billingUrl: 'https://max.com/account', description: 'HBO streaming', color: '#002BE7', tags: ['streaming', 'hbo'], popularity: 83, verified: true, active: true },
    { name: 'Paramount+', slug: 'paramount-plus', type: ProviderType.ENTERTAINMENT, categoryId: categoryMap.get('entertainment'), logoUrl: 'https://placeholder.com/icons/paramount', websiteUrl: 'https://paramountplus.com', billingUrl: 'https://paramountplus.com/account', description: 'Paramount streaming', color: '#0064FF', tags: ['streaming', 'movies'], popularity: 75, verified: true, active: true },
    { name: 'Peacock', slug: 'peacock', type: ProviderType.ENTERTAINMENT, categoryId: categoryMap.get('entertainment'), logoUrl: 'https://placeholder.com/icons/peacock', websiteUrl: 'https://peacocktv.com', billingUrl: 'https://peacocktv.com/account', description: 'NBC streaming', color: '#000000', tags: ['streaming', 'nbc'], popularity: 73, verified: true, active: true },
    { name: 'Crunchyroll', slug: 'crunchyroll', type: ProviderType.ENTERTAINMENT, categoryId: categoryMap.get('entertainment'), logoUrl: 'https://placeholder.com/icons/crunchyroll', websiteUrl: 'https://crunchyroll.com', billingUrl: 'https://crunchyroll.com/acct', description: 'Anime streaming', color: '#F47521', tags: ['streaming', 'anime'], popularity: 80, verified: true, active: true },
    { name: 'Tidal', slug: 'tidal', type: ProviderType.ENTERTAINMENT, categoryId: categoryMap.get('music'), logoUrl: 'https://placeholder.com/icons/tidal', websiteUrl: 'https://tidal.com', billingUrl: 'https://my.tidal.com', description: 'High-fidelity music', color: '#000000', tags: ['music', 'audio'], popularity: 60, verified: true, active: true },
    { name: 'SoundCloud', slug: 'soundcloud', type: ProviderType.ENTERTAINMENT, categoryId: categoryMap.get('music'), logoUrl: 'https://placeholder.com/icons/soundcloud', websiteUrl: 'https://soundcloud.com', billingUrl: 'https://soundcloud.com/settings/billing', description: 'Audio platform', color: '#FF5500', tags: ['music', 'indie'], popularity: 70, verified: true, active: true },
    { name: 'Midjourney', slug: 'midjourney', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('ai'), logoUrl: 'https://placeholder.com/icons/midjourney', websiteUrl: 'https://midjourney.com', billingUrl: 'https://midjourney.com/account', description: 'AI image generation', color: '#FFFFFF', tags: ['ai', 'art'], popularity: 85, verified: true, active: true },
    { name: 'Claude', slug: 'claude', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('ai'), logoUrl: 'https://placeholder.com/icons/claude', websiteUrl: 'https://anthropic.com', billingUrl: 'https://console.anthropic.com/settings/billing', description: 'AI assistant', color: '#D4B895', tags: ['ai', 'anthropic'], popularity: 82, verified: true, active: true },
    { name: 'Vercel', slug: 'vercel', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('developer-tools'), logoUrl: 'https://placeholder.com/icons/vercel', websiteUrl: 'https://vercel.com', billingUrl: 'https://vercel.com/dashboard/billing', description: 'Frontend cloud', color: '#000000', tags: ['dev', 'hosting'], popularity: 80, verified: true, active: true },
    { name: 'AWS', slug: 'aws', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('developer-tools'), logoUrl: 'https://placeholder.com/icons/aws', websiteUrl: 'https://aws.amazon.com', billingUrl: 'https://console.aws.amazon.com/billing', description: 'Cloud computing', color: '#FF9900', tags: ['dev', 'cloud'], popularity: 95, verified: true, active: true },
    { name: 'JetBrains', slug: 'jetbrains', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('developer-tools'), logoUrl: 'https://placeholder.com/icons/jetbrains', websiteUrl: 'https://jetbrains.com', billingUrl: 'https://account.jetbrains.com', description: 'Developer IDEs', color: '#000000', tags: ['dev', 'ide'], popularity: 85, verified: true, active: true },
    { name: 'Duolingo', slug: 'duolingo', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('education'), logoUrl: 'https://placeholder.com/icons/duolingo', websiteUrl: 'https://duolingo.com', billingUrl: 'https://duolingo.com/settings/super', description: 'Language learning', color: '#58CC02', tags: ['education', 'languages'], popularity: 90, verified: true, active: true },
    { name: 'Coursera', slug: 'coursera', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('education'), logoUrl: 'https://placeholder.com/icons/coursera', websiteUrl: 'https://coursera.org', billingUrl: 'https://coursera.org/my-purchases', description: 'Online courses', color: '#0056D2', tags: ['education', 'learning'], popularity: 80, verified: true, active: true },
    { name: 'Udemy', slug: 'udemy', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('education'), logoUrl: 'https://placeholder.com/icons/udemy', websiteUrl: 'https://udemy.com', billingUrl: 'https://udemy.com/user/edit-profile/', description: 'Online learning platform', color: '#A435F0', tags: ['education', 'courses'], popularity: 82, verified: true, active: true },
    { name: 'Skillshare', slug: 'skillshare', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('education'), logoUrl: 'https://placeholder.com/icons/skillshare', websiteUrl: 'https://skillshare.com', billingUrl: 'https://skillshare.com/settings/payments', description: 'Creative classes', color: '#00FF84', tags: ['education', 'creative'], popularity: 75, verified: true, active: true },
    { name: 'YNAB', slug: 'ynab', type: ProviderType.UTILITY, categoryId: categoryMap.get('finance'), logoUrl: 'https://placeholder.com/icons/ynab', websiteUrl: 'https://youneedabudget.com', billingUrl: 'https://app.youneedabudget.com/settings', description: 'Personal budgeting', color: '#005A6F', tags: ['finance', 'budget'], popularity: 70, verified: true, active: true },
    { name: 'QuickBooks', slug: 'quickbooks', type: ProviderType.UTILITY, categoryId: categoryMap.get('finance'), logoUrl: 'https://placeholder.com/icons/quickbooks', websiteUrl: 'https://quickbooks.intuit.com', billingUrl: 'https://qbo.intuit.com/app/account', description: 'Accounting software', color: '#2CA01C', tags: ['finance', 'accounting'], popularity: 80, verified: true, active: true },
    { name: 'NordVPN', slug: 'nordvpn', type: ProviderType.UTILITY, categoryId: categoryMap.get('security'), logoUrl: 'https://placeholder.com/icons/nordvpn', websiteUrl: 'https://nordvpn.com', billingUrl: 'https://my.nordaccount.com/billing', description: 'VPN service', color: '#4687FF', tags: ['security', 'vpn'], popularity: 85, verified: true, active: true },
    { name: 'ExpressVPN', slug: 'expressvpn', type: ProviderType.UTILITY, categoryId: categoryMap.get('security'), logoUrl: 'https://placeholder.com/icons/expressvpn', websiteUrl: 'https://expressvpn.com', billingUrl: 'https://expressvpn.com/my-account', description: 'VPN service', color: '#DA291C', tags: ['security', 'vpn'], popularity: 82, verified: true, active: true },
    { name: '1Password', slug: '1password', type: ProviderType.UTILITY, categoryId: categoryMap.get('security'), logoUrl: 'https://placeholder.com/icons/1password', websiteUrl: 'https://1password.com', billingUrl: 'https://my.1password.com/billing', description: 'Password manager', color: '#0572EC', tags: ['security', 'passwords'], popularity: 88, verified: true, active: true },
    { name: 'Bitwarden', slug: 'bitwarden', type: ProviderType.UTILITY, categoryId: categoryMap.get('security'), logoUrl: 'https://placeholder.com/icons/bitwarden', websiteUrl: 'https://bitwarden.com', billingUrl: 'https://vault.bitwarden.com', description: 'Open source password manager', color: '#175DDC', tags: ['security', 'passwords'], popularity: 85, verified: true, active: true },
    { name: 'Todoist', slug: 'todoist', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('productivity'), logoUrl: 'https://placeholder.com/icons/todoist', websiteUrl: 'https://todoist.com', billingUrl: 'https://todoist.com/app/settings/billing', description: 'Task management', color: '#E44332', tags: ['productivity', 'tasks'], popularity: 80, verified: true, active: true },
    { name: 'Evernote', slug: 'evernote', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('productivity'), logoUrl: 'https://placeholder.com/icons/evernote', websiteUrl: 'https://evernote.com', billingUrl: 'https://evernote.com/Settings.action', description: 'Note taking', color: '#00A82D', tags: ['productivity', 'notes'], popularity: 75, verified: true, active: true },
    { name: 'Trello', slug: 'trello', type: ProviderType.SOFTWARE, categoryId: categoryMap.get('productivity'), logoUrl: 'https://placeholder.com/icons/trello', websiteUrl: 'https://trello.com', billingUrl: 'https://trello.com/my/billing', description: 'Visual project management', color: '#0052CC', tags: ['productivity', 'projects'], popularity: 85, verified: true, active: true },
  ];

  for (const provider of providersData) {
    await prisma.provider.upsert({
      where: { slug: provider.slug },
      update: provider,
      create: provider,
    });
    console.log(`Upserted provider: ${provider.name}`);
  }

  console.log('Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
